openapi: 3.0.0
info:
  version: '0.001'
  title: joke api - just upload auth
  description: ''
tags:
  - name: admins
    description: Secured Admin-only calls
  - name: developers
    description: Operations available to regular developers
paths: 
  /joke:
    post:
      tags:
        - admins
      summary: adds a joke
      operationId: addJoke
      description: Adds a joke to the system
      parameters:
        - in: header
          name: x-admin
          schema: 
            type: string
          required: true
        
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - joke
                - punchline
              properties:
                joke:
                  type: string
                  example: Knock Knock. Who's there? Hike. Hike Who?
                  description: The joke
                punchline:
                  example: I didn't know you liked Japanese poetry.
                  description: The punchline.
                  type: string   
                category:
                  example: knockKnock
                  description: category of the joke (allowed categories TBD)
                  type: string
                testing:
                  example: this is a test field
                  description: im trying to break stuff
                  type: string
      responses:
        '200':
          description: item created
          content:
            application/vnd.json:
              schema:
                $ref: '#/components/schemas/Joke'
        '401':
          description: 'not authorized'
        '422':
          description: 'parameter missing'
    get:
      tags:
        - developers
      summary: retrieve a joke
      operationId: getaJoke
      parameters:
        - name: category
          in: query
          description: The category of the joke.
          example: knockknock
          required: false
          schema: 
            type: string
      responses:
        '200':
          description: joke found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Joke'
            
        '400':
          description: 'No Joke.  Seriously. No jokes matched your Request.'
components:
  schemas:
    Joke:
      type: object
      required:
        - id
        - dateAdded
        - joke
        - punchline
        - thumbsUp
        - thumbsDown
        - category
      properties:
        id:
          type: string
          example: ce0b9fbe-7ad8-11eb-9439-0242ac130002
          description: The id of the Joke. Assigned when added.
        joke:
          type: string
          example: Why did the chicken cross the road?
          description: The lead-in to the joke.
        punchline:
          type: string
          example: To get to the other side.
          description: This bit should make you laugh :).
        category:
          type: string
          example: Classic
          description: the category of the joke.
        thumbsUp:
          type: integer
          example: 2
          description: Count of upvotes for the joke.
        thumbsDown:
          type: integer
          example: 4
          description: Count of down votes for the joke.
        dateAdded:
          type: string
          format: date-time
          example: '2016-08-29T09:12:33.001Z'

servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://.../dougsillars/joke_api_0001/0.001