name: Deploy documentation

on:
  push:
    branches:
      - main

jobs:
  deploy-doc:
    name: Deploy API doc on Bump
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy API documentation
        uses: bump-sh/github-action@0.2
        with:
          doc: 18b7b128-6396-411a-bac7-47967d5a8879
          token: ${{secrets.BUMP_TOKEN}}
          file: /joke_api_0001.yaml
